### ISSUE TITLE
Home Assistant configuration?

### ISSUE THREAD

**Issue by rubengargar** [335iguy/diy-multisensor-cat-feeder#1]
Hi!

I'm trying to build something like this also! Can you share the Home Assistant for this? Mainly the automation. I see you have the input number from the Esphome example, but I'm trying to figure out the automation to drop the food daily.

Another interesting repository: https://github.com/lance36/catFeeder

**Comment by Molecule5537** [comment]
My build was inspired by lance36. The configuration isn't available currently. However, I used NodeRed node for a set time to trigger the cat feeder. I'll update the configuration over the weekend. I had to stop the project because the D shaped pin on the pinwheel of the feeder broke and i am in progress of getting a metal one made.

**Comment by Molecule5537** [comment]
Updates with Node-red configuration and new addition to the readme.
